#!/usr/bin/env ruby

require "ruby_differ"

old_version = ARGV.shift
new_version = ARGV.shift
path = ARGV.shift

strage_path = RubyDiffer::StragePath.new(path)
RubyDiffer::Save.diff(old_version, new_version, starge_path)
